### Albemarle Sound (AS) Meteorologic Station - Analysis

### Data:
From the CSI Met station in Albemarle Sound:
- Air Temperature
- Barometric Pressure
- Relative Humidity
- Dew Point Temperature
- Vapor Pressure
- Wind Speed
- Wind Direction
- Wind Gusts
- Water Level
    
From the ACoE Field Research Facility:
- Wind Speed
- Wind Direction
- Wind Gusts
    
From National Weather Service Stations at the Manteo/Dare Regional and Wright Brothers First Flight Airports:
- Air Temperature
- Barometric Pressure
- Relative Humidity
- Dew Point Temperature
- Wind Speed
- Wind Direction

From the USACOE Currituck Sound Station (added 6/23/2016):
- Wind Speed
- Wind Direction
- Temperature
- Relative Humidity

In [1]:
import pandas
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as md

In [2]:
# set data file location(s) via paths and names:

fpath='/Users/paulp/Documents/projects/ASMet/data/'
f_csi='CR1000Data_JanMarch2009.csv' #'OcnMetDataMarchJune2016.csv'
f_oi='oregionInletJanMarch2009.csv'
f_frf='FRFWindData_MarchJune2016.csv'
f_ffap='FFAPMarJune2016dat.csv'
f_mdap='ManteoDareAPMarJune2016dat.csv'

In [87]:
# load data into pandas data frames and wrangle into useful forms:

# set column name lists:
#csi_columns=["Yr","Mon","Day","TIMESTAMP","RECORD","Air_Temp","Baro_Press","Rel_Hum","Dew_Pt","Vpr_Press","Windspeed","Winddirection","StDev","Windgust","Wtr_Lvl_Avg"]
csi_columns=["year","month","day","hour","minute","second","RECORD","Air_Temp","Baro_Press","Rel_Hum","Dew_Pt","Vpr_Press","Windspeed","Winddirection","StDev","Windgust","Wtr_Lvl_Avg"]


oi_columns=['year','month','day','hour','minute','WDIR','WSPD','GST','WVHT','DPD','APD','MWD','PRES','ATMP','WTMP','DEWP','VIS','TIDE']
##yr,mo,dy,hr,mn,degT,m/s,m/s,,m,sec,sec,degT,hPa,degC,degC,degC,mi,,ft

frf_columns=['Yr','Mon','Day','TimeEST','GaugeID','Winddirection','Windspeed','Windgust']
neic_columns=['USAF','NCDC','Yr','Mon','Day','Time','I','Type','Winddirection','WinddirQ','WindI','Windspeed','WindspdQ','temp','TempQ',\
              'Dewpoint','DewpointQ','Baropress','BaropressQ','Relhumidity']

# load CSI Albemarle Sound Met Station data:
df_csi=pandas.read_csv(fpath+f_csi, sep=',', header=1, names=csi_columns )

# load Oregon Inlet Marina Met Station data:
df_oi=pandas.read_csv(fpath+f_oi, sep=',', header=1, names=oi_columns )

# load FRF Pier anemometer data:
df_frf=pandas.read_csv(fpath+f_frf, sep=',', names=frf_columns)

# load Manteo/Dare Regional Airport data (replace missing values 999s with NaN):
df_mdap=pandas.read_csv(fpath+f_mdap, sep=',', names=neic_columns).replace(999, np.NaN)

# load First Flight Airport data (replace missing values 999s with NaN):
df_ffap=pandas.read_csv(fpath+f_ffap, sep=',', names=neic_columns).replace(999, np.NaN)

# load FRF Currituck Sound data:
df_frfcs=pandas.read_table(fpath+'FRFCSStation/FRF_EOP_Wind20160406.txt', header=0, delimiter='\s+' ).dropna()


# convert FRF, Manteo/Dare, and Currituck Snd wind speeds from meters per second to knots   (1m/s = 1.94384kt)
df_frf.Windspeed=pandas.to_numeric(df_frf.Windspeed*1.94384)
df_frf.Windgust=pandas.to_numeric(df_frf.Windgust*1.94384)

df_oi = df_oi[df_oi.WSPD != 99.0]
df_oi.WSPD=pandas.to_numeric(df_oi.WSPD*1.94384)

df_mdap.Windspeed=pandas.to_numeric(df_mdap.Windspeed*1.94384)
df_ffap.Windspeed=pandas.to_numeric(df_ffap.Windspeed*1.94384)

df_frfcs.Speed=pandas.to_numeric(df_frfcs.Speed*1.94384)

In [88]:
df_oi.describe()

,year,month,day,hour,minute,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
count,21184.0,21184.000000,21184.000000,21184.000000,21184.000000,21184.000000,21184.000000,21184.000000,21184.0,21184.0,21184.0,21184.0,21184.000000,21184.000000,21184.000000,21184.0,21184.0,21184.0
mean,2009.0,2.014586,15.545223,11.507270,26.964879,196.690852,10.163171,7.300821,99.0,99.0,99.0,999.0,1020.559526,6.930174,655.106056,999.0,99.0,99.0
std,0.0,0.827024,8.734581,6.924723,17.244903,129.944250,4.667592,3.477990,0.0,0.0,0.0,0.0,8.062460,4.679865,471.466309,0.0,0.0,0.0
min,2009.0,1.000000,1.000000,0.000000,0.000000,1.000000,0.194384,0.200000,99.0,99.0,99.0,999.0,993.400000,-5.400000,2.500000,999.0,99.0,99.0
25%,2009.0,1.000000,8.000000,5.000000,12.000000,63.000000,6.609056,4.800000,99.0,99.0,99.0,999.0,1015.400000,4.300000,10.400000,999.0,99.0,99.0
50%,2009.0,2.000000,16.000000,12.000000,24.000000,205.000000,9.913584,7.100000,99.0,99.0,99.0,999.0,1021.300000,7.200000,999.000000,999.0,99.0,99.0
75%,2009.0,3.000000,23.000000,18.000000,42.000000,307.000000,13.412496,9.700000,99.0,99.0,99.0,999.0,1026.500000,10.000000,999.000000,999.0,99.0,99.0
max,2009.0,3.000000,31.000000,23.000000,54.000000,999.000000,33.628432,99.000000,99.0,99.0,99.0,999.0,1037.300000,25.400000,999.000000,999.0,99.0,99.0

In [7]:
import dateutil

fig1=plt.figure(figsize=(14,7))
ax1=fig1.add_subplot(1,1,1)

csiMarch31 = df_csi.loc[(df_csi.Mon == 3) & (df_csi.Day == 31)]
dates = [dateutil.parser.parse(t) for t in csiMarch31.TIMESTAMP]

xfmt = md.DateFormatter('%H:%M:%S')
ax1.xaxis.set_major_formatter(xfmt)
#frf = df_frf.groupby(['Mon','Day'])
#curr = df_frfcs.groupby(['Mon','Day'])

ax1.plot(dates, csiMarch31.Windspeed, label='CSI AS Met')
#ax1.plot(frf.days, frf.Windspeed, c='r', label='ACOE FRF Pier')

#ax1.plot(curr.days, curr.Speed, c='orange', label='ACOE Currituck Snd')
print(csiMarch31)
#plt.show()

Empty DataFrame
Columns: [Yr, Mon, Day, TIMESTAMP, RECORD, Air_Temp_Avg, Baro_Press_Avg, Rel_Hum_Avg, Dew_Pt_Avg, Vpr_Press_Avg, Windspeed, Winddirection, StDev, Windgust, Wtr_Lvl_Avg]
Index: []

In [56]:
#print(df_csi)  #print( df_csi.loc[df_csi.Day == np.isnan] )

In [89]:
# set the day lists for each station data set (you'll use these for plotting):
def AssignDayNumber2Observation(d):
    if(d.Mon == 1):
        return(d.Day)
    if(d.Mon == 2):
        return(d.Day+31)   # use 31 for a prior 31 day long month
    if(d.Mon == 3):
        return(d.Day+59)   # 61 for post April
    if(d.Mon == 6):
        return(d.Day+92)
    
    #df_csi['days']=df_csi.Mon+df_csi.Day*0.01
#df_csi['days'] = df_csi.apply(AssignDayNumber2Observation, axis=1) #.astype(int)
#df_oi['days'] = df_oi.apply(AssignDayNumber2Observation, axis=1).astype(int)
#df_frf['days'] = df_frf.apply(AssignDayNumber2Observation, axis=1).astype(int)
#df_mdap['days'] = df_mdap.apply(AssignDayNumber2Observation, axis=1).astype(int)
#df_ffap['days'] = df_ffap.apply(AssignDayNumber2Observation, axis=1).astype(int)
#df_frfcs['days'] = df_frfcs.apply(AssignDayNumber2Observation, axis=1).astype(int)



# convert all readings of interest to hourly averages from 12 March, 2016 to 14 June, 2016, eh?
# aggregate data first on month, and then by day, to compute a daily average of met params
#csi = df_csi.groupby(['Mon','Day']).mean()
#oi = df_oi.groupby(['Mon','Day','Hr','Min'])
#frf = df_frf.groupby(['Mon','Day']).mean()
#mdap = df_mdap.groupby(['Mon','Day']).mean()
#ffap = df_ffap.groupby(['Mon','Day']).mean()
#curr = df_frfcs.groupby(['Mon','Day']).mean()

#df['Combined_ID'] = df[['ID_1','ID_2','ID_3']].fillna('').sum(axis=1)
#df['newcol'] = df['col1'].map(str) + df['col2'].map(str)

df_csi.TIMESTAMP = pandas.to_datetime(df_csi[['year', 'month', 'day', 'hour', 'minute']])
df_oi.TIMESTAMP = pandas.to_datetime(df_oi[['year', 'month', 'day', 'hour', 'minute']])
#print(df_oi.TIMESTAMP)

# deprecated bits:
# both the CSI and FRF stations have 95 days of data reported between 3/12 and 6/14
#csi_days=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]

# the Manteo/Dare Airport has only 80 days of data reported between 3/12 and 6/14
#md_days=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]

# the Wright Brothers/First Flight Airport has 90 days of data reported between 3/12 and 6/14
#ff_days=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 18, 19, 20, 21, 22, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]

# the USACOE's Currituck Sound station has 79 days, but they begin on 1 April (there is no March data)
#curr_days=[25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]

In [61]:
from datetime import datetime

#print( datetime(2009,1,1,12,49,0) )
#print(df_csi.Day.astype(int))

### Plot Station Wind Speeds

In [ ]:
fig1=plt.figure(figsize=(14,7))
ax1=fig1.add_subplot(1,1,1)

ax1.scatter(df_csi.dayNumber, df_csi.Windspeed, label='CSI AS Met')
ax1.plot(df_oi.dayNumber, df_oi.WSPD, label='Oregon Inlet')
#ax1.plot(frf.days, frf.Windspeed, c='r', label='ACOE FRF Pier')
#ax1.plot(mdap.days, mdap.Windspeed, c='g', label='Manteo/Dare Airport')
#ax1.plot(ffap.days, ffap.Windspeed, c='y', label='First Flight Airport')
#ax1.plot(curr.days, curr.Speed, c='orange', label='ACOE Currituck Snd')

ax1.set_xlabel('Days since 12 March, 2016 (up to 6/14)')
ax1.set_ylabel('Windspeed (Knots)')
ax1.set_title('Daily Averaged Station Windspeeds (Data from 3/12 to 6/14, 2016)')
plt.legend(loc='upper right')
plt.show()

#plt.savefig('/Users/paulp/Documents/projects/ASMet/windspd.pdf', bbox_inches='tight')

In [101]:
### Plot wind speed based on a TIMESTAMP column

import dateutil
import datetime as dt

fig1=plt.figure(figsize=(14,7))
ax1=fig1.add_subplot(1,1,1)

#csiMarch31 = df_csi.loc[(df_csi.Mon == 3) & (df_csi.Day == 31)]
#CSI_dates = md.date2num(df_csi.TIMESTAMP)

#CSI_dates=[dt.date.fromtimestamp(ts) for ts in df_csi.TIMESTAMP]
#CSI_dates = [dateutil.parser.parse(t) for t in df_csi.TIMESTAMP]
#OI_dates = [dateutil.parser.parse(t) for t in oi_df.TIMESTAMP]

xfmt = md.DateFormatter('%Y-%m-%d')
ax1.xaxis.set_major_formatter(xfmt)

plt.plot(df_csi.TIMESTAMP, df_csi.Windspeed, label='CSI AS Met')
ax1.plot(df_oi.TIMESTAMP, df_oi.WSPD, color='r', label='Oregon Inlet')
ax1.set_xlabel('Date (Jan 01 thru March 31, 2009)')
ax1.set_ylabel('Wind Speed (kts)')
plt.legend(loc='upper right')
plt.show()  #plt.savefig('/Users/paulp/Documents/projects/ASMet/windspd2009.pdf', bbox_inches='tight')

In [95]:
df_oi.describe()

,year,month,day,hour,minute,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
count,21184.0,21184.000000,21184.000000,21184.000000,21184.000000,21184.000000,21184.000000,21184.000000,21184.0,21184.0,21184.0,21184.0,21184.000000,21184.000000,21184.000000,21184.0,21184.0,21184.0
mean,2009.0,2.014586,15.545223,11.507270,26.964879,196.690852,10.163171,7.300821,99.0,99.0,99.0,999.0,1020.559526,6.930174,655.106056,999.0,99.0,99.0
std,0.0,0.827024,8.734581,6.924723,17.244903,129.944250,4.667592,3.477990,0.0,0.0,0.0,0.0,8.062460,4.679865,471.466309,0.0,0.0,0.0
min,2009.0,1.000000,1.000000,0.000000,0.000000,1.000000,0.194384,0.200000,99.0,99.0,99.0,999.0,993.400000,-5.400000,2.500000,999.0,99.0,99.0
25%,2009.0,1.000000,8.000000,5.000000,12.000000,63.000000,6.609056,4.800000,99.0,99.0,99.0,999.0,1015.400000,4.300000,10.400000,999.0,99.0,99.0
50%,2009.0,2.000000,16.000000,12.000000,24.000000,205.000000,9.913584,7.100000,99.0,99.0,99.0,999.0,1021.300000,7.200000,999.000000,999.0,99.0,99.0
75%,2009.0,3.000000,23.000000,18.000000,42.000000,307.000000,13.412496,9.700000,99.0,99.0,99.0,999.0,1026.500000,10.000000,999.000000,999.0,99.0,99.0
max,2009.0,3.000000,31.000000,23.000000,54.000000,999.000000,33.628432,99.000000,99.0,99.0,99.0,999.0,1037.300000,25.400000,999.000000,999.0,99.0,99.0

In [94]:
df_csi.describe()

,year,month,day,hour,minute,second,RECORD,Air_Temp,Baro_Press,Rel_Hum,Dew_Pt,Vpr_Press,Windspeed,Winddirection,StDev,Windgust,Wtr_Lvl_Avg
count,4316.0,4316.000000,4316.000000,4316.000000,4316.000000,4316.0,4316.00000,4316.000000,4316.000000,4316.000000,4316.000000,4316.000000,4316.000000,4316.000000,4316.000000,4316.000000,4316.000000
mean,2009.0,2.000927,15.535681,11.500000,19.006951,0.0,10856.50000,6.929745,1018.394578,71.041182,5.624716,0.739898,12.244328,139.711295,3.646198,14.871949,1.236273
std,0.0,0.829915,8.713829,6.923234,15.001736,0.0,1246.06621,4.000287,8.169341,16.450063,3.770510,0.323277,8.368449,119.730616,3.529193,10.158811,0.009792
min,2009.0,1.000000,1.000000,0.000000,4.000000,0.0,8699.00000,0.001000,991.000000,30.090000,0.000000,0.126000,0.000000,0.000000,0.000000,0.000000,1.201726
25%,2009.0,1.000000,8.000000,5.750000,4.000000,0.0,9777.75000,4.027000,1013.000000,57.987500,2.543250,0.492000,6.208500,27.217500,1.861750,7.522750,1.229095
50%,2009.0,2.000000,15.000000,11.000000,34.000000,0.0,10856.50000,6.593000,1019.000000,72.200000,5.157500,0.723000,12.525000,115.150000,3.340000,14.960000,1.236017
75%,2009.0,3.000000,23.000000,18.000000,34.000000,0.0,11935.25000,9.432500,1024.000000,86.000000,8.312500,0.943000,17.992500,230.000000,4.849750,21.372500,1.241676
max,2009.0,3.000000,31.000000,23.000000,34.000000,0.0,13014.00000,20.350000,1036.000000,95.900000,20.000000,2.040000,42.110000,360.000000,63.710000,53.260000,1.275205

### Plot Station Wind Directions

In [ ]:
fig2=plt.figure(figsize=(14,7))
ax2=fig2.add_subplot(1,1,1)

ax2.plot(csi.days, csi.Winddirection, label='CSI AS Met')
ax2.plot(frf.days, frf.Winddirection, c='r', label='FRF Pier')
ax2.plot(mdap.days, mdap.Winddirection, c='g', label='Manteo/Dare Airport')
ax2.plot(ffap.days, ffap.Winddirection, c='y', label='First Flight Airport')
ax2.plot(curr.days, curr.Dir, c='orange', label='ACOE Currituck Snd')

ax2.set_xlabel('Days since 12 March, 2016 (up to 6/14)')
ax2.set_ylabel('Wind Direction (Degrees off North)')
ax2.set_title('Daily Averaged Station Wind Directions  (Data from 3/12 to 6/14, 2016)')
plt.legend(loc='upper right')
#plt.show()

#plt.savefig('/Users/paulp/Documents/projects/ASMet/winddir.pdf', bbox_inches='tight')

### Plot Station Wind Gusts

In [ ]:
fig3=plt.figure(figsize=(14,7))
ax3=fig3.add_subplot(1,1,1)

ax3.plot(csi.days, csi.Windgust, label='CSI AS Met')
ax3.plot(frf.days, frf.Windgust, c='r', label='FRF Pier')
#ax3.plot(md_days, mdap.Winddirection, c='g', label='Manteo/Dare Airport')
#ax3.plot(ff_days, ffap.Winddirection, c='y', label='First Flight Airport')

ax3.set_xlabel('Days since 12 March, 2016')
ax3.set_ylabel('Wind Gusts (Knots)')
ax3.set_title('Daily Averaged Station Wind Gusts  (Data from 3/12 to 6/14, 2016)')
plt.legend(loc='upper right')
#plt.show()

#plt.savefig('/Users/paulp/Documents/projects/ASMet/windgusts.pdf', bbox_inches='tight')

In [ ]:
# build a data frame for the US Army Engineers Currituck Sound Station Temps (and Relative Humidity, though we're not 
# yet using it).

# notes: the data came as three separate files, once each for the months of April, May, and June. We concatenate these
# at the OS level and remove extraneous headers prior to loading into the data frame:

# $ cat CS02_TempHumidity_201604.txt CS02_TempHumidity_201605.txt CS02_TempHumidity_201606.txt \
#   > CS02_TempHumidity_20160406.txt


df_cs_tmpH=pandas.read_table(fpath+'FRFCSStation/CS02_TempHumidity_20160406.txt', header=0, sep='\s+').dropna()

df_cs_tmpH['days'] = df_cs_tmpH.apply(AssignDayNumber2Observation, axis=1).astype(int)

df_currituckSndTemps=df_cs_tmpH.groupby(['Mon', 'Day']).mean()


# the USACOE's Currituck Sound station has 79 days, but they begin on 1 April (there is no March data)
currtmp_days=[47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]

In [ ]:
print(len(df_currituckSndTemps), len(currtmp_days) )

### Plot Station Temperatures

In [ ]:
fig4=plt.figure(figsize=(14,7))
ax4=fig4.add_subplot(1,1,1)

ax4.plot(csi.days, csi.Air_Temp_Avg, label='CSI AS Met')
ax4.plot(mdap.days, mdap.temp, c='g', label='Manteo/Dare Airport')
ax4.plot(ffap.days, ffap.temp, c='y', label='First Flight Airport')
ax4.plot(df_currituckSndTemps.days, df_currituckSndTemps.Temp, c='orange', label='ACOE Currituck Snd')

ax4.set_xlabel('Days since 12 March, 2016 (up to 6/24)')
ax4.set_ylabel('Temperatures (C)')
ax4.set_title('Daily Averaged Station Air Temperatures  (Data from 3/12 to 6/14, 2016)')
plt.legend(loc='lower right')
#plt.show()

plt.savefig('/Users/paulp/Documents/projects/ASMet/airtemps.pdf', bbox_inches='tight')

### Plot Station Atmospheric Pressures

In [ ]:
fig5=plt.figure(figsize=(14,7))
ax5=fig5.add_subplot(1,1,1)

ax5.plot(csi_days, csi.Baro_Press_Avg, label='CSI AS Met')
#plt.plot(csi_days, frf.Windgust, c='r', label='FRF Pier')
#plt.plot(md_days, mdap.temp, c='g', label='Manteo/Dare Airport')
#plt.plot(ff_days, ffap.temp, c='y', label='First Flight Airport')

ax5.set_xlabel('Days since 12 March, 2016')
ax5.set_ylabel('Barometric Pressure (mb)')
ax5.set_title('Daily Averaged Station Air Barometric Pressures  (Data from 3/12 to 6/14, 2016)')
plt.legend(loc='upper right')
plt.show()

#plt.savefig('/Users/paulp/Documents/projects/ASMet/airpress.pdf', bbox_inches='tight')

In [ ]:
# load the entire ocean met data archive from the CSI Met ASS:

cols=["TIMESTAMP","RECORD","Air_Temp_Avg","Baro_Press_Avg","Rel_Hum_Avg","Dew_Pt_Avg","Vpr_Press_Avg","Wind_Speed","Wind_Dir","StDev","Wind_Gust","Wtr_Lvl_Avg"]

allcsi = pandas.read_csv(fpath+'CR1000_ocean_met_data.dat', sep=',', skiprows=4, names=cols)

In [ ]:
# PLOT WATER LEVELS:

# x = np.linspace(1,len(df_csi), len(df_csi))

fig6=plt.figure(figsize=(14,7))
ax6=fig6.add_subplot(1,1,1)

ax6.scatter(df_csi.RECORD, df_csi.Wtr_Lvl_Avg, label='CSI Met ASS')
#plt.plot(csi_days, frf.Windgust, c='r', label='FRF Pier')
#plt.plot(md_days, mdap.temp, c='g', label='Manteo/Dare Airport')
#plt.plot(ff_days, ffap.temp, c='y', label='First Flight Airport')

#ax6.set_xlabel('Sample Record Number (showing all samples captured from 12/19, 2009 to 6/14, 2016, inclusive)')
#ax6.set_ylabel('Pressure (bars)')
#ax6.set_title('Sample Averaged Station Surface Water Levels (Pressure)')
#plt.legend(loc='upper left')
plt.grid()
#plt.show()

plt.savefig('/Users/paulp/Documents/projects/ASMet/waterlvl.pdf', bbox_inches='tight')

In [ ]:
# WATER LEVELS HISTOGRAM

df_csi.Wtr_Lvl_Avg.hist(bins=50, color='r')

plt.xlabel('Avg. Water Level Change (bars)')
plt.ylabel('Frequency')
plt.title('Avg. Water Level Changes (3/12 thru 6/14, 2016)')
plt.show()

In [ ]:
fp = open('/Users/paulp/Documents/projects/ASMet/data/CR1000_ocean_met_data.dat', 'r')
fo = open('/Users/paulp/Documents/projects/ASMet/data/CR1000_ocean_met_data2.dat', 'w')
for index, row in enumerate(fp):
    if(index != 0):
        a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q = row.rstrip().split(',')
        ws=str(a)+','+str(b)+','+str(c)+','+str(d)+','+str(e)+','+str(a)+','+str(a)+','+str(a)+','+str(a)+','+ \
           str(a)+','+str(a)+','+str(a)+','+str(a)+','+str(a)+','+str(a)+','+str(a)+'\n'

In [48]:
## Checking for and reporting on MET STATION UP AND DOWN TIMES, from January 1, 2009 to June 14, 2016
#
import datetime
from matplotlib import dates


# source data: /Users/paulp/Documents/projects/ASMet/data/CR1000_ocean_met_data.dat
sf='/Users/paulp/Documents/projects/ASMet/data/CR1000_ocean_met_data.dat'
#
# Step 1: load the source data to a pandas data frame
ocn_met = pandas.read_csv(sf, header=0)

# duplicate the year, month, and day fields to preserve through the aggregation step to follow...

# read the first three columns in the df (year, month, and day) and transform these into a timestamp to be used for 
# plotting...I hope!

# Step 2: aggregate the data frame based on Yr, Mon, and Day:
ocn_met_ = ocn_met.groupby(['year','month','day']).mean()

#ocn_met_.Y=ocn_met_.Y.astype(int)
#ocn_met_.M=ocn_met_.M.astype(int)
#ocn_met_.D=ocn_met_.D.astype(int)

#ocn_met_['Dat']=
#print(str(ocn_met_.Y))  ###+'-'+str(ocn_met_.M)+'-'+str(ocn_met_.D)

sensors=['AirTemp','BaroPress','RelHum','VprPress','WindSpd','WindDir','WindGust','WtrLevel']
for index, row in ocn_met_.iterrows():
    for sensor in sensors:
        if(row[sensor] != 0):
            nv = 1   
        if(row[sensor] == 0):
            nv = 0
        ocn_met_.set_value(index,sensor,nv)

ocn_met_.reset_index(inplace=True)

ocn_met_.loc[:,'AirTemp'] *= 100
ocn_met_.loc[:,'BaroPress'] *= 200
ocn_met_.loc[:,'RelHum'] *= 300
ocn_met_.loc[:,'WindSpd'] *= 400
ocn_met_.loc[:,'WindDir'] *= 22
ocn_met_.loc[:,'WindGust'] *= 20
ocn_met_.loc[:,'WtrLevel'] *= 500


ocn_met_['date']= ocn_met_.apply(lambda x:datetime.datetime.strptime("{0} {1} {2}".format(x['year'].astype(int),x['month'].astype(int), x['day'].astype(int)), "%Y %m %d"),axis=1)
#ocn_met.index= ocn_met['date']


fig7=plt.figure(figsize=(21,7))
ax7=fig7.add_subplot(1,1,1)
# Convert dates to numbers
x = [dates.date2num(t) for t in ocn_met_.date]

plt.scatter(x,ocn_met_.AirTemp, color='k', s=1, label='Sensor Active')
plt.scatter(x,ocn_met_.BaroPress, color='k', s=1)
plt.scatter(x,ocn_met_.RelHum, color='k', s=1)
plt.scatter(x,ocn_met_.WindSpd, color='k', s=1)
#plt.scatter(x, ocn_met_.WindDir, color='blue', label='Wind Direction')
#plt.scatter(x, ocn_met_.WindGust, color='orange', label='Wind Gust')
plt.scatter(x,ocn_met_.WtrLevel, color='k', s=1)


# Setup the DateFormatter for the x axis
date_format = dates.DateFormatter('%D')
ax7.xaxis.set_major_formatter(date_format)

# Rotates the labels to fit
fig7.autofmt_xdate()

ax7.set_xlim([datetime.date(2009, 1, 1), datetime.date(2016, 6, 15)])
ax7.set_ylim(0, 700)
ax7.set_yticklabels([])

#plt.legend(loc='upper right')
#plt.show()

plt.savefig('/Users/paulp/Documents/projects/ASMet/sensorsUpTimes.svg', format='svg', dpi=1200, bbox_inches='tight')


#df.loc[df['column_name'] == some_value]

#ocn_met_

# TO DO
# set values in ocn_met_ to integers and multple by 2, 3, 4, 5 and so on to get vertical offsets so that all can be
# plotted on a single figure
# use different colors, maybe for each
# remove y labels and tics
# adjust x label dates for more clarity/info
# export to Afinity for polish--maybe

In [41]:
ocn_met.apply(lambda x:'%s %s %s' % (x['year'].astype(int),x['month'], x['day']),axis=1)

0         2009 1.0 1.0
1         2009 1.0 1.0
2         2009 1.0 1.0
3         2009 1.0 1.0
4         2009 1.0 1.0
5         2009 1.0 1.0
6         2009 1.0 1.0
7         2009 1.0 1.0
8         2009 1.0 1.0
9         2009 1.0 1.0
10        2009 1.0 1.0
11        2009 1.0 1.0
12        2009 1.0 1.0
13        2009 1.0 1.0
14        2009 1.0 1.0
15        2009 1.0 1.0
16        2009 1.0 1.0
17        2009 1.0 1.0
18        2009 1.0 1.0
19        2009 1.0 1.0
20        2009 1.0 1.0
21        2009 1.0 1.0
22        2009 1.0 1.0
23        2009 1.0 1.0
24        2009 1.0 1.0
25        2009 1.0 1.0
26        2009 1.0 1.0
27        2009 1.0 1.0
28        2009 1.0 1.0
29        2009 1.0 1.0
             ...
65517    2016 6.0 14.0
65518    2016 6.0 14.0
65519    2016 6.0 14.0
65520    2016 6.0 14.0
65521    2016 6.0 14.0
65522    2016 6.0 15.0
65523    2016 6.0 15.0
65524    2016 6.0 15.0
65525    2016 6.0 15.0
65526    2016 6.0 15.0
65527    2016 6.0 15.0
65528    2016 6.0 15.0
65529    2016 6.0 15.0
65530    2016 6.0 15.0
65531    2016 6.0 15.0
65532    2016 6.0 15.0
65533    2016 6.0 15.0
65534    2016 6.0 15.0
65535    2016 6.0 15.0
65536    2016 6.0 15.0
65537    2016 6.0 15.0
65538    2016 6.0 15.0
65539    2016 6.0 15.0
65540    2016 6.0 15.0
65541    2016 6.0 15.0
65542    2016 6.0 15.0
65543    2016 6.0 15.0
65544    2016 6.0 15.0
65545    2016 6.0 15.0
65546    2016 6.0 15.0
dtype: object

In [22]:
ocn_met_

,year,month,day,Hr,Min,Sec,Rec,AirTemp,BaroPress,RelHum,DewPt,VprPress,WindSpd,WindDir,StDev,WindGust,WtrLevel,date
0,2009,1,1,11.500000,19.000000,0.0,8721.5,1.0,2.0,3.0,9.373271,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-01
1,2009,1,2,11.500000,19.000000,0.0,8769.5,1.0,2.0,3.0,4.495750,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-02
2,2009,1,3,11.500000,19.000000,0.0,8817.5,1.0,2.0,3.0,3.597146,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-03
3,2009,1,4,11.500000,19.000000,0.0,8865.5,1.0,2.0,3.0,4.855937,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-04
4,2009,1,5,11.500000,19.000000,0.0,8913.5,1.0,2.0,3.0,9.265667,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-05
5,2009,1,6,11.500000,19.000000,0.0,8961.5,1.0,2.0,3.0,8.106917,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-06
6,2009,1,7,11.500000,19.000000,0.0,9009.5,1.0,2.0,3.0,11.039208,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-07
7,2009,1,8,11.500000,19.000000,0.0,9057.5,1.0,2.0,3.0,1.546250,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-08
8,2009,1,9,11.500000,19.000000,0.0,9105.5,1.0,2.0,3.0,5.586083,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-09
9,2009,1,10,11.500000,19.000000,0.0,9153.5,1.0,2.0,3.0,3.501354,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-10
10,2009,1,11,11.500000,19.000000,0.0,9201.5,1.0,2.0,3.0,8.337667,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-11
11,2009,1,12,11.500000,19.000000,0.0,9249.5,1.0,2.0,3.0,1.870563,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-12
12,2009,1,13,11.500000,19.000000,0.0,9297.5,1.0,2.0,3.0,4.337208,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-13
13,2009,1,14,11.500000,19.000000,0.0,9345.5,1.0,2.0,3.0,3.299146,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-14
14,2009,1,15,11.500000,19.000000,0.0,9393.5,1.0,2.0,3.0,1.673417,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-15
15,2009,1,16,11.500000,19.000000,0.0,9441.5,1.0,2.0,3.0,13.371104,1.0,0.0,0.0,0.000000,0.0,7.0,2009-01-16
16,2009,1,17,11.244444,19.333333,0.0,9488.0,1.0,2.0,3.0,13.191600,1.0,4.0,5.0,4.459378,6.0,7.0,2009-01-17
17,2009,1,18,11.500000,19.000000,0.0,9534.5,1.0,2.0,3.0,4.121750,1.0,4.0,5.0,4.350229,6.0,7.0,2009-01-18
18,2009,1,19,11.500000,19.000000,0.0,9582.5,1.0,2.0,3.0,2.336437,1.0,4.0,5.0,6.361000,6.0,7.0,2009-01-19
19,2009,1,20,11.500000,19.000000,0.0,9630.5,1.0,2.0,3.0,3.002146,1.0,4.0,5.0,4.530000,6.0,7.0,2009-01-20
20,2009,1,21,11.500000,19.000000,0.0,9678.5,1.0,2.0,3.0,8.870646,1.0,4.0,5.0,6.017229,6.0,7.0,2009-01-21
21,2009,1,22,11.500000,19.000000,0.0,9726.5,1.0,2.0,3.0,5.336083,1.0,4.0,5.0,3.310292,6.0,7.0,2009-01-22
22,2009,1,23,11.500000,19.000000,0.0,9774.5,1.0,2.0,3.0,0.906896,1.0,4.0,5.0,2.340771,6.0,7.0,2009-01-23
23,2009,1,24,11.500000,19.000000,0.0,9822.5,1.0,2.0,3.0,3.591521,1.0,4.0,5.0,2.800875,6.0,7.0,2009-01-24
24,2009,1,25,11.500000,19.000000,0.0,9870.5,1.0,2.0,3.0,3.556083,1.0,4.0,5.0,4.611396,6.0,7.0,2009-01-25
25,2009,1,26,11.500000,19.000000,0.0,9918.5,1.0,2.0,3.0,0.758167,1.0,4.0,5.0,4.006479,6.0,7.0,2009-01-26
26,2009,1,27,11.500000,19.000000,0.0,9966.5,1.0,2.0,3.0,2.338354,1.0,4.0,5.0,3.688042,6.0,7.0,2009-01-27
27,2009,1,28,11.500000,19.000000,0.0,10014.5,1.0,2.0,3.0,6.714063,1.0,4.0,5.0,5.392000,6.0,7.0,2009-01-28
28,2009,1,29,11.500000,19.000000,0.0,10062.5,1.0,2.0,3.0,3.558375,1.0,4.0,5.0,3.006625,6.0,7.0,2009-01-29
29,2009,1,30,11.500000,19.000000,0.0,10110.5,1.0,2.0,3.0,1.790021,1.0,4.0,5.0,5.257146,6.0,7.0,2009-01-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1359,2016,5,17,11.500000,19.000000,0.0,4884.5,1.0,2.0,3.0,13.980833,1.0,4.0,5.0,4.406813,6.0,7.0,2016-05-17
1360,2016,5,18,11.500000,19.000000,0.0,4932.5,1.0,2.0,3.0,13.732292,1.0,4.0,5.0,4.852188,6.0,7.0,2016-05-18
1361,2016,5,19,11.500000,19.000000,0.0,4980.5,1.0,2.0,3.0,10.354771,1.0,4.0,5.0,5.627458,6.0,7.0,2016-05-19
1362,2016,5,20,11.500000,19.000000,0.0,5028.5,1.0,2.0,3.0,9.592417,1.0,4.0,5.0,4.375771,6.0,7.0,2016-05-20
1363,2016,5,21,11.500000,19.000000,0.0,5076.5,1.0,2.0,3.0,16.817083,1.0,4.0,5.0,4.649812,6.0,7.0,2016-05-21
1364,2016,5,22,11.500000,19.000000,0.0,5124.5,1.0,2.0,3.0,12.911250,1.0,4.0,5.0,5.626437,6.0,7.0,2016-05-22
1365,2016,5,23,11.500000,19.000000,0.0,5172.5,1.0,2.0,3.0,11.462292,1.0,4.0,5.0,5.859083,6.0,7.0,2016-05-23
1366,2016,5,24,11.500000,19.000000,0.0,5220.5,1.0,2.0,3.0,13.434375,1.0,4.0,5.0,3.059354,6.0,7.0,2016-05-24
1367,2016,5,25,11.500000,19.000000,0.0,5268.5,1.0,2.0,3.0,15.310833,1.0,4.0,5.0,4.977875,6.0,7.0,2016-05-25
1368,2016,5,26,11.500000,19.000000,0.0,5316.5,1.0,2.0,3.0,17.368333,1.0,4.0,5.0,2.972625,6.0,7.0,2016-05-26
1369,2016,5,27,11.500000,19.000000,0.0,5364.5,1.0,2.0,3.0,16.328125,1.0,4.0,5.0,5.972271,6.0,7.0,2016-05-27
1370,2016,5,28,11.500000,19.000000,0.0,5412.5,1.0,2.0,3.0,18.660625,1.0,4.0,5.0,4.813750,6.0,7.0,2016-05-28
1371,2016,5,29,11.500000,19.000000,0.0,5460.5,1.0,2.0,3.0,21.090208,1.0,4.0,5.0,7.816000,6.0,7.0,2016-05-29
1372,2016,5,30,11.500000,19.000000,0.0,5508.5,1.0,2.0,3.0,20.263958,1.0,4.0,5.0,7.277667,6.0,7.0,2016-05-30
1373,2016,5,31,11.500000,19.000000,0.0,5556.5,1.0,2.0,3.0,19.120833,1.0,4.0,5.0,5.691854,6.0,7.0,2016-05-31
1374,2016,6,1,11.500000,19.000000,0.0,5604.5,1.0,2.0,3.0,20.584583,1.0,4.0,5.0,4.763292,6.0,7.0,2016-06-01
1375,2016,6,2,11.500000,19.000000,0.0,5652.5,1.0,2.0,3.0,20.350833,1.0,4.0,5.0,3.998896,6.0,7.0,2016-06-02
1376,2016,6,3,11.500000,19.000000,0.0,5700.5,1.0,2.0,3.0,20.101875,1.0,4.0,5.0,6.879688,6.0,7.0,2016-06-03
1377,2016,6,4,11.500000,19.000000,0.0,5748.5,1.0,2.0,3.0,21.396875,1.0,4.0,5.0,6.940438,6.0,7.0,2016-06-04
1378,2016,6,5,11.500000,19.000000,0.0,5796.5,1.0,2.0,3.0,21.725000,1.0,4.0,5.0,3.161333,6.0,7.0,2016-06-05
1379,2016,6,6,11.500000,19.000000,0.0,5844.5,1.0,2.0,3.0,21.407083,1.0,4.0,5.0,3.500500,6.0,0.0,2016-06-06
1380,2016,6,7,11.489362,18.680851,0.0,5892.0,1.0,2.0,3.0,19.566383,1.0,4.0,5.0,7.911745,6.0,7.0,2016-06-07
1381,2016,6,8,11.500000,19.000000,0.0,5939.5,1.0,2.0,3.0,12.615708,1.0,4.0,5.0,5.706042,6.0,0.0,2016-06-08
1382,2016,6,9,11.500000,19.000000,0.0,5987.5,1.0,2.0,3.0,7.945563,1.0,4.0,5.0,7.610771,6.0,0.0,2016-06-09
1383,2016,6,10,11.500000,19.000000,0.0,6035.5,1.0,2.0,3.0,10.938979,1.0,4.0,5.0,6.589521,6.0,0.0,2016-06-10
1384,2016,6,11,11.500000,19.000000,0.0,6083.5,1.0,2.0,3.0,19.126250,1.0,4.0,5.0,3.476500,6.0,7.0,2016-06-11
1385,2016,6,12,11.500000,19.000000,0.0,6131.5,1.0,2.0,3.0,21.101875,1.0,4.0,5.0,2.741792,6.0,7.0,2016-06-12
1386,2016,6,13,11.531915,19.319149,0.0,6179.0,1.0,2.0,3.0,12.910426,1.0,4.0,5.0,7.399681,6.0,7.0,2016-06-13
1387,2016,6,14,11.500000,19.000000,0.0,6226.5,1.0,2.0,3.0,15.678125,1.0,4.0,5.0,5.570979,6.0,7.0,2016-06-14
1388,2016,6,15,5.760000,18.400000,0.0,6263.0,1.0,2.0,3.0,17.546400,1.0,4.0,5.0,6.021040,6.0,7.0,2016-06-15

In [10]:
dic={'C1':[7,9,11,14,21],'C2':[21,5,7,9,1] }

df_1 = pandas.DataFrame(dic, columns=['C1','C2'])

df_1
df_1.loc[:,'C1'] = df_1.loc[:,'C1'] + 1
df_1

   C1  C2
0   8  21
1  10   5
2  12   7
3  15   9
4  22   1